{
    'name': 'Tuni_Matcha',
    'version': '1.0',
    'author': 'Đức Tín',
    'category': 'All',
    'summary': 'Tính doanh thu và lợi nhuận quán nước',
    'depends': ['web','base','mail'],
    'data': [
        'views/Tuni_assets_view.xml',
        'views/Tuni_menu_view.xml',
        'views/Tuni_sale_view.xml',
        'views/Tuni_finance_view.xml',
        'views/Tuni_purchase_view.xml',
        'views/Tuni_menu_segment_report_view.xml',
        'views/Tuni_menu_segment_report_milk_view.xml',
        'views/Tuni_rent_report_view.xml',
        'views/Tuni_employee_views.xml',
        'views/Tuni_attendance_views.xml',
        'views/Tuni_shift_views.xml',
        'views/Tuni_salary_views.xml',
        'views/Tuni_order_view.xml',
        'views/Tuni_customer_view.xml',
        'views/Tuni_chat_view.xml',
        'views/Tuni_promotion_view.xml',
        'views/Tuni_promotion_gift_view.xml',
        'views/Tuni_inventory_view.xml',
        'views/Tuni_chart_view.xml',
        'data/Tuni_promotion_cron.xml',
        'data/Report_tuni_order.xml',
        'data/ir_sequence_data.xml',
        'security/ir.model.access.csv',

    ],
    'installable': True,
    'application': True,
}